// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix
package oval_sc

import (
	"encoding/xml"
	"github.com/0intro/scap/pkg/scap/models/oval"
)

// Element
type DnscacheItem struct {
	XMLName xml.Name `xml:"dnscache_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	DomainName *EntityItemStringType `xml:"domain_name"`

	Ttl *EntityItemIntType `xml:"ttl"`

	IpAddress []EntityItemIPAddressStringType `xml:"ip_address"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type FileItem struct {
	XMLName xml.Name `xml:"file_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	Filepath *EntityItemStringType `xml:"filepath"`

	Path *EntityItemStringType `xml:"path"`

	Filename *EntityItemStringType `xml:"filename"`

	Type *EntityItemStringType `xml:"type"`

	GroupId *FileItemGroupId `xml:"group_id"`

	UserId *FileItemUserId `xml:"user_id"`

	ATime *FileItemATime `xml:"a_time"`

	CTime *FileItemCTime `xml:"c_time"`

	MTime *FileItemMTime `xml:"m_time"`

	Size *EntityItemIntType `xml:"size"`

	Suid *EntityItemBoolType `xml:"suid"`

	Sgid *EntityItemBoolType `xml:"sgid"`

	Sticky *EntityItemBoolType `xml:"sticky"`

	Uread *EntityItemBoolType `xml:"uread"`

	Uwrite *EntityItemBoolType `xml:"uwrite"`

	Uexec *EntityItemBoolType `xml:"uexec"`

	Gread *EntityItemBoolType `xml:"gread"`

	Gwrite *EntityItemBoolType `xml:"gwrite"`

	Gexec *EntityItemBoolType `xml:"gexec"`

	Oread *EntityItemBoolType `xml:"oread"`

	Owrite *EntityItemBoolType `xml:"owrite"`

	Oexec *EntityItemBoolType `xml:"oexec"`

	HasExtendedAcl *EntityItemBoolType `xml:"has_extended_acl"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type FileextendedattributeItem struct {
	XMLName xml.Name `xml:"fileextendedattribute_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	Filepath *EntityItemStringType `xml:"filepath"`

	Path *EntityItemStringType `xml:"path"`

	Filename *EntityItemStringType `xml:"filename"`

	AttributeName *EntityItemStringType `xml:"attribute_name"`

	Value *EntityItemAnySimpleType `xml:"value"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type GconfItem struct {
	XMLName xml.Name `xml:"gconf_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	Key *EntityItemStringType `xml:"key"`

	Source *EntityItemStringType `xml:"source"`

	Type *EntityItemGconfTypeType `xml:"type"`

	IsWritable *EntityItemBoolType `xml:"is_writable"`

	ModUser *EntityItemStringType `xml:"mod_user"`

	ModTime *EntityItemIntType `xml:"mod_time"`

	IsDefault *EntityItemBoolType `xml:"is_default"`

	Value []EntityItemAnySimpleType `xml:"value"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type InetdItem struct {
	XMLName xml.Name `xml:"inetd_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	Protocol *EntityItemStringType `xml:"protocol"`

	ServiceName *EntityItemStringType `xml:"service_name"`

	ServerProgram *EntityItemStringType `xml:"server_program"`

	ServerArguments *EntityItemStringType `xml:"server_arguments"`

	EndpointType *EntityItemEndpointType `xml:"endpoint_type"`

	ExecAsUser *EntityItemStringType `xml:"exec_as_user"`

	WaitStatus *EntityItemWaitStatusType `xml:"wait_status"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type InterfaceItem struct {
	XMLName xml.Name `xml:"interface_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	Name *EntityItemStringType `xml:"name"`

	Type *EntityItemInterfaceType `xml:"type"`

	HardwareAddr *EntityItemStringType `xml:"hardware_addr"`

	InetAddr *EntityItemIPAddressStringType `xml:"inet_addr"`

	BroadcastAddr *EntityItemIPAddressStringType `xml:"broadcast_addr"`

	Netmask *EntityItemIPAddressStringType `xml:"netmask"`

	Flag []EntityItemStringType `xml:"flag"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type PasswordItem struct {
	XMLName xml.Name `xml:"password_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	Username *EntityItemStringType `xml:"username"`

	Password *EntityItemStringType `xml:"password"`

	UserId *PasswordItemUserId `xml:"user_id"`

	GroupId *PasswordItemGroupId `xml:"group_id"`

	Gcos *EntityItemStringType `xml:"gcos"`

	HomeDir *EntityItemStringType `xml:"home_dir"`

	LoginShell *EntityItemStringType `xml:"login_shell"`

	LastLogin *EntityItemIntType `xml:"last_login"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type ProcessItem struct {
	XMLName xml.Name `xml:"process_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	Command *EntityItemStringType `xml:"command"`

	ExecTime *EntityItemStringType `xml:"exec_time"`

	Pid *EntityItemIntType `xml:"pid"`

	Ppid *EntityItemIntType `xml:"ppid"`

	Priority *EntityItemIntType `xml:"priority"`

	Ruid *EntityItemIntType `xml:"ruid"`

	SchedulingClass *EntityItemStringType `xml:"scheduling_class"`

	StartTime *EntityItemStringType `xml:"start_time"`

	Tty *EntityItemStringType `xml:"tty"`

	UserId *EntityItemIntType `xml:"user_id"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type Process58Item struct {
	XMLName xml.Name `xml:"process58_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	CommandLine *EntityItemStringType `xml:"command_line"`

	ExecTime *EntityItemStringType `xml:"exec_time"`

	Pid *EntityItemIntType `xml:"pid"`

	Ppid *EntityItemIntType `xml:"ppid"`

	Priority *EntityItemIntType `xml:"priority"`

	Ruid *EntityItemIntType `xml:"ruid"`

	SchedulingClass *EntityItemStringType `xml:"scheduling_class"`

	StartTime *EntityItemStringType `xml:"start_time"`

	Tty *EntityItemStringType `xml:"tty"`

	UserId *EntityItemIntType `xml:"user_id"`

	ExecShield *EntityItemBoolType `xml:"exec_shield"`

	Loginuid *EntityItemIntType `xml:"loginuid"`

	PosixCapability []EntityItemCapabilityType `xml:"posix_capability"`

	SelinuxDomainLabel *EntityItemStringType `xml:"selinux_domain_label"`

	SessionId *EntityItemIntType `xml:"session_id"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type RoutingtableItem struct {
	XMLName xml.Name `xml:"routingtable_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	Destination *EntityItemIPAddressType `xml:"destination"`

	Gateway *EntityItemIPAddressType `xml:"gateway"`

	Flags []EntityItemRoutingTableFlagsType `xml:"flags"`

	InterfaceName *EntityItemStringType `xml:"interface_name"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type RunlevelItem struct {
	XMLName xml.Name `xml:"runlevel_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	ServiceName *EntityItemStringType `xml:"service_name"`

	Runlevel *EntityItemStringType `xml:"runlevel"`

	Start *EntityItemBoolType `xml:"start"`

	Kill *EntityItemBoolType `xml:"kill"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type SccsItem struct {
	XMLName xml.Name `xml:"sccs_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	Filepath *EntityItemStringType `xml:"filepath"`

	Path *EntityItemStringType `xml:"path"`

	Filename *EntityItemStringType `xml:"filename"`

	ModuleName *EntityItemStringType `xml:"module_name"`

	ModuleType *EntityItemStringType `xml:"module_type"`

	Release *EntityItemStringType `xml:"release"`

	Level *EntityItemStringType `xml:"level"`

	Branch *EntityItemStringType `xml:"branch"`

	Sequence *EntityItemStringType `xml:"sequence"`

	WhatString *EntityItemStringType `xml:"what_string"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type ShadowItem struct {
	XMLName xml.Name `xml:"shadow_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	Username *EntityItemStringType `xml:"username"`

	Password *EntityItemStringType `xml:"password"`

	ChgLst *ShadowItemChgLst `xml:"chg_lst"`

	ChgAllow *ShadowItemChgAllow `xml:"chg_allow"`

	ChgReq *ShadowItemChgReq `xml:"chg_req"`

	ExpWarn *ShadowItemExpWarn `xml:"exp_warn"`

	ExpInact *ShadowItemExpInact `xml:"exp_inact"`

	ExpDate *ShadowItemExpDate `xml:"exp_date"`

	Flag *ShadowItemFlag `xml:"flag"`

	EncryptMethod *EntityItemEncryptMethodType `xml:"encrypt_method"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type SymlinkItem struct {
	XMLName xml.Name `xml:"symlink_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	Filepath EntityItemStringType `xml:"filepath"`

	CanonicalPath EntityItemStringType `xml:"canonical_path"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type SysctlItem struct {
	XMLName xml.Name `xml:"sysctl_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	Name *EntityItemStringType `xml:"name"`

	Value []EntityItemAnySimpleType `xml:"value"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type UnameItem struct {
	XMLName xml.Name `xml:"uname_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	MachineClass *EntityItemStringType `xml:"machine_class"`

	NodeName *EntityItemStringType `xml:"node_name"`

	OsName *EntityItemStringType `xml:"os_name"`

	OsRelease *EntityItemStringType `xml:"os_release"`

	OsVersion *EntityItemStringType `xml:"os_version"`

	ProcessorType *EntityItemStringType `xml:"processor_type"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type XinetdItem struct {
	XMLName xml.Name `xml:"xinetd_item"`

	Id oval.ItemIDPattern `xml:"id,attr"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	Protocol *EntityItemStringType `xml:"protocol"`

	ServiceName *EntityItemStringType `xml:"service_name"`

	Flags []EntityItemStringType `xml:"flags"`

	NoAccess []EntityItemStringType `xml:"no_access"`

	OnlyFrom []EntityItemIPAddressStringType `xml:"only_from"`

	Port *EntityItemIntType `xml:"port"`

	Server *EntityItemStringType `xml:"server"`

	ServerArguments *EntityItemStringType `xml:"server_arguments"`

	SocketType *EntityItemStringType `xml:"socket_type"`

	Type []EntityItemXinetdTypeStatusType `xml:"type"`

	User *EntityItemStringType `xml:"user"`

	Wait *EntityItemBoolType `xml:"wait"`

	Disabled *EntityItemBoolType `xml:"disabled"`

	Message []oval.MessageType `xml:"message"`
}

// Element
type FileItemGroupId struct {
	XMLName xml.Name `xml:"group_id"`

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`
}

// Element
type FileItemUserId struct {
	XMLName xml.Name `xml:"user_id"`

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`
}

// Element
type FileItemATime struct {
	XMLName xml.Name `xml:"a_time"`

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`
}

// Element
type FileItemCTime struct {
	XMLName xml.Name `xml:"c_time"`

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`
}

// Element
type FileItemMTime struct {
	XMLName xml.Name `xml:"m_time"`

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`
}

// Element
type PasswordItemUserId struct {
	XMLName xml.Name `xml:"user_id"`

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`
}

// Element
type PasswordItemGroupId struct {
	XMLName xml.Name `xml:"group_id"`

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`
}

// Element
type ShadowItemChgLst struct {
	XMLName xml.Name `xml:"chg_lst"`

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`
}

// Element
type ShadowItemChgAllow struct {
	XMLName xml.Name `xml:"chg_allow"`

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`
}

// Element
type ShadowItemChgReq struct {
	XMLName xml.Name `xml:"chg_req"`

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`
}

// Element
type ShadowItemExpWarn struct {
	XMLName xml.Name `xml:"exp_warn"`

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`
}

// Element
type ShadowItemExpInact struct {
	XMLName xml.Name `xml:"exp_inact"`

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`
}

// Element
type ShadowItemExpDate struct {
	XMLName xml.Name `xml:"exp_date"`

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`
}

// Element
type ShadowItemFlag struct {
	XMLName xml.Name `xml:"flag"`

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`
}

// XSD ComplexType declarations

type EntityItemCapabilityType struct {
	XMLName xml.Name

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	InnerXml string `xml:",innerxml"`
}

type EntityItemEndpointType struct {
	XMLName xml.Name

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	InnerXml string `xml:",innerxml"`
}

type EntityItemGconfTypeType struct {
	XMLName xml.Name

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	InnerXml string `xml:",innerxml"`
}

type EntityItemRoutingTableFlagsType struct {
	XMLName xml.Name

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	InnerXml string `xml:",innerxml"`
}

type EntityItemXinetdTypeStatusType struct {
	XMLName xml.Name

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	InnerXml string `xml:",innerxml"`
}

type EntityItemWaitStatusType struct {
	XMLName xml.Name

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	InnerXml string `xml:",innerxml"`
}

type EntityItemEncryptMethodType struct {
	XMLName xml.Name

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	InnerXml string `xml:",innerxml"`
}

type EntityItemInterfaceType struct {
	XMLName xml.Name

	Datatype oval.DatatypeEnumeration `xml:"datatype,attr,omitempty"`

	Mask bool `xml:"mask,attr,omitempty"`

	Status StatusEnumeration `xml:"status,attr,omitempty"`

	InnerXml string `xml:",innerxml"`
}

// XSD SimpleType declarations
